/**
 * Represents the form data required to submit a new talent request.
 */
export type TalentRequestData = {
  /** The name of the company hiring. */
  companyName: string;
  /** The contact email for the request. */
  email: string;
  /** The role or proficiency level being sought (e.g., "Senior Frontend"). */
  proficiency: string;
  /** Detailed description of the requirements or project. */
  description: string;
  /** * The security token generated by Cloudflare Turnstile.
   * Required for backend verification to prevent spam.
   */
  "cf-turnstile-response": string;
};

/**
 * Standard response structure from the API.
 */
export type ApiResponse = {
  /** Indicates if the operation completed successfully. */
  success: boolean;
  /** Optional error message if the operation failed. */
  error?: string;
};

/**
 * Sends a talent request to the backend proxy API.
 *
 * This function handles the network call to the local Astro API route (`/api/send-talent`),
 * which securely proxies the request to the Cloudflare Worker. It catches network
 * errors and parses non-200 responses into a standardized error format.
 *
 * @param data - The talent request form data to be sent.
 * @returns A promise that resolves to the API response object.
 */
export async function sendTalentRequest(
  data: TalentRequestData,
): Promise<ApiResponse> {
  try {
    // We call the local proxy endpoint, NOT the worker directly.
    // The proxy handles the secret tokens and security checks.
    const response = await fetch("/api/send-talent", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify(data),
    });

    if (!response.ok) {
      // Attempt to parse the specific error message from the JSON response
      const errorData = (await response
        .json()
        .catch(() => ({}))) as ApiResponse;
      throw new Error(errorData.error || `Error: ${response.status}`);
    }

    return (await response.json()) as ApiResponse;
  } catch (err) {
    console.error("Failed to send email:", err);
    return {
      success: false,
      error: err instanceof Error ? err.message : "Network error",
    };
  }
}
